title: Foukous
description:

date_format: "%d/%m/%Y"
locale: fr
logo: /assets/images/logo.png
minimal_mistakes_skin: default
remote_theme: mmistakes/minimal-mistakes@4.24.0
search: true

comments:
  provider: giscus
  giscus:
    repo_id: R_kgDOGyaOZQ
    category_name: Announcements
    category_id: DIC_kwDOGyaOZc4CBSU5
    discussion_term: pathname
    lang: fr
    reactions_enabled: 1
    theme: light

baseurl: ""
paginate: 10
paginate_path: /page:num/
permalink: /:categories/:title/
repository: "lfabreges/lfabreges.github.io"
url: "https://lfabreges.github.io"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: false
      comments: true
      classes: wide
      layout: single
      read_time: true
      related: true
      share: true
  - scope:
      path: "_pages"
      type: pages
    values:
      author_profile: false
      classes: wide
      layout: single

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/lfabreges"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/lfabreges"

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
